### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by khabdrick**
complete project

### CODE REVIEW

**Comment by Youngestdev** [comment]
@khabdrick, is this application up to date?

**Comment by khabdrick** [comment]
@Youngestdev yes
But I'll have to update it again when I make changes to the blog itself

**Comment by Youngestdev** [comment]
Alright, do that then.

**Comment by khabdrick** [comment]
@Youngestdev Done with the update

**Comment by khabdrick** [comment]
Not sure, isn't this supposed to be merged?
@Youngestdev

**Pull request merged**
